server:
  port: 9000

spring:
  profiles:
    include: oauth
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: picasso
    password: 1234
 
mybatis:
  type-aliases-package: com.project.picasso.model
  mapper-locations:
  - classpath:mapper/**/*.xml
  
